#!/usr/bin/env bash
#
# Create a virtualenv. Note that python 3.6 is currently the minimal requirement
#
# Stop on error, rather than continue and trash the environment
set -e
#
# Default to 3.8 but allow override
DEFAULT_PYTHON_VER=3.10
PYTHON_VER=${1:-$DEFAULT_PYTHON_VER}
#
python${PYTHON_VER} -m venv env
#
source env/bin/activate
#
pip3 install --upgrade pip setuptools wheel
pip3 install -r requirements.txt
pip3 install -r dev_requirements.txt
#
python3 setup.py develop
